Initial React framework setup, sidebar, hash routing, registration tab.
jiaweizhang/duke-programming-contest pull request #29
Opened 2016-10-16 18:57 UTC by kyh8

2016-10-16 19:35 UTC, jiaweizhang requested changes

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/css/main.css
> +body {
Do we plan on ever separating this into multiple css files?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/App.js
> +            <Route path="/~kevinhe/dpc" component={Content}>
Why is there a /~kevinhe in the path lol?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Content.js
> +          width: (this.state.dimensions.width - 60) + 'px',
any way we can move this into the CSS?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/index.html
> +  <head>
let's look into using google analytics to track accesses and use. I'll make an issue separately.

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Content.js
> +  calculateDimensions() {
Can we move these hardcoded values to CSS somehow?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Home.js
> +            left: '50px',
belongs in css

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Problems.js
> +    title: 'My Google Inteview Question'
change this before Google sues us.

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Registration.js
> +    if (email.length == 0 || password.length == 0) {
will create issue to do more front-end validation

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Registration.js
> +const TITLE_HEIGHT = 100;
Is there a way to move this to CSS and use css-classes to retrieve these values?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Sidebar.js
> +            onClick={this.selectTab.bind(this, index)}
Isn't this deprecated?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/js/Util.js
> +  static calculateDimensions(xOffset, yOffset) {
Why do we have "calculateDimensions" all over the place?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/package.json
> +  "license": "ISC",
change to GPL 3.0

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/package.json
> +    "build": "browserify -t [ babelify ] main.js  | uglifyjs -mc warnings=false > bundle.js"
does uglifyjs perform tree-balancing and minimization?

2016-10-16 19:35 UTC, jiaweizhang commented on src/main/webapp/index.html
> +    <link rel="icon" href="assets/code-brackets.png">
I assume none of these images/icons are copyrighted and we can use?

2016-10-16 19:36 UTC, jiaweizhang commented
Also, let's remove bundle.js and add instructions on how others can run the front-end and how they can access it via localhost

2016-10-20 03:07 UTC, kyh8 commented on src/main/webapp/css/main.css
> +body {
Yes, eventually if we need to. Right now just putting it in one file

2016-10-20 03:08 UTC, kyh8 commented on src/main/webapp/js/App.js
> +            <Route path="/~kevinhe/dpc" component={Content}>
oops

2016-10-20 03:10 UTC, kyh8 commented on src/main/webapp/js/Content.js
> +  calculateDimensions() {
It has to be done on resize, which is a js thing

2016-10-20 03:10 UTC, kyh8 commented on src/main/webapp/js/Content.js
> +          width: (this.state.dimensions.width - 60) + 'px',
Same as above

2016-10-20 03:11 UTC, kyh8 commented on src/main/webapp/index.html
> +    <link rel="icon" href="assets/code-brackets.png">
Yes

2016-10-20 03:13 UTC, kyh8 commented on src/main/webapp/js/Problems.js
> +    title: 'My Google Inteview Question'
This is dummy data

2016-10-20 03:15 UTC, kyh8 commented on src/main/webapp/js/Registration.js
> +    if (email.length == 0 || password.length == 0) {
This is not the final thing lel

2016-10-20 03:15 UTC, kyh8 commented on src/main/webapp/js/Sidebar.js
> +            onClick={this.selectTab.bind(this, index)}
onClick?

2016-10-20 03:15 UTC, kyh8 commented on src/main/webapp/package.json
> +    "build": "browserify -t [ babelify ] main.js  | uglifyjs -mc warnings=false > bundle.js"
Dunno dude

2016-10-20 05:45 UTC, jiaweizhang commented on src/main/webapp/js/Content.js
> +  calculateDimensions() {
But can't you do like "update to the value contained by this class"

2016-10-24 18:20 UTC, kyh8 commented
Please merge

2016-10-24 22:29 UTC, jiaweizhang approved these changes

2016-10-24 22:29 UTC, merged